name       : qt6.5d
version    : 6.5.1
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qt3d-everywhere-src-6.5.1.tar.xz : 7e54e1e810ba57b510002b899d9b63d611b287691731739665c1a1b26139689b
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6.5D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
clang      : yes
builddeps  :
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(assimp)
rundeps    :
    - devel :
        - assimp-devel
setup      : |
    %patch -p1 < $pkgfiles/qt3d-quickextras-3dlogic-namespace.patch
    %cmake_ninja -DQT_FEATURE_qt3d_rhi_renderer=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
